language: python

python:
  -3.8

install:
  - pip install pipenv pytest
  - pipenv install
  - pipenv sync
  - pytest              # <  

  

script:
 - flake8
 - pytest libsensedata --cov=libsensedata
 